# -*- coding: utf-8 -*-
"""MEDIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ripXkdQYgx0QMo-6FTZkNeifwrwo3-Nq
"""

from pyspark.sql import SparkSession

from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Estadística_media").getOrCreate()

A_notas = spark.read.csv("nota_alumno.csv")

A_notas.show()

A_notas = spark.read.csv("nota_alumno.csv", header=True, inferSchema=True)

A_notas = A_notas.withColumnRenamed("_c0", "Nombre").withColumnRenamed("_c1", "Nota")

A_notas.show()

mean_nota = A_notas.select(mean("Nota")).first()[0]

print("el promedio de las notas es:", mean_nota)